# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BTM
                                 A QGIS plugin
  Analyzes benthic terrain for the purposes of classifying surficial seafloor characteristics that may be used in studies of benthic habitat, geomorphology, prediction of benthic fish species distribution, marine protected area design, and more
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-04
        copyright            : (C) 2023 by Tim Le Bas, National Oceanography Centre, Southampton. UK.
        email                : tim.lebas@noc.ac.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BTM class from file BTM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .BTM import BTM
    return BTM(iface)
